apiVersion: "spec.keptn.sh/0.2.2"
kind: "Shipyard"
metadata:
  name: "shipyard-digitales"
spec:
  stages:
    - name: "quality-gate"
      sequences:
        - name: "delivery"
          tasks:
            - name: "test"
              properties:
                teststrategy: "performance_1"
            - name: "evaluation"
        - name: "evaluation"
          tasks:
            - name: "evaluation"
